import { cn } from "@/lib/utils";
import { ClerkProvider, SignInButton,
  SignedIn,
  SignedOut,
  UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

const IBMPlex = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-plex",
});

export const metadata: Metadata = {
  title: "SnappyWiz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={cn("font-IBMPLex antialiased", IBMPlex.variable)}>
       
        <ClerkProvider appearance={{
          variables: {colorPrimary : '#333'}
        }}>
         
          {children}
    </ClerkProvider>
        </body>
      </html>
  );
}
